### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by jah2488** [buckspencer/tic_tac_toe#1]
Good job on completing the assignment. Below are a few fixes that I would like to see made.

`board.rb:5` -- Indentation is wrong and block needs spacing
* `9` Why are strings being added? Do they need to be?
* `10` Too far indented

`player.rb: 14-15`
* x and y are never used and only y is returned. Is this intentional?
                                                                                        

`tic_tac_toe.rb:59`
* Check your while loop. Do all of those prints and checks need to be there?

### Specs ###
 __Invalid Syntax.__
- Won't even run.
- x doesn't exist. 
- `it` with no `end`. 
- `'describ'`
- Lets make sure that files that are not being used are still valid syntax

**Comment by buckspencer** [comment]
Great, I'l get into that.

On Tue, Jan 13, 2015 at 8:33 PM, Justin Herrick <notifications@github.com>
wrote:

> Good job on completing the assignment. Below are a few fixes that I would
> like to see made.
>
> board.rb:5 -- Indentation is wrong and block needs spacing
>
>    - 9 Why are strings being added? Do they need to be?
>    - 10 Too far indented
>
> player.rb: 14-15
>
>    - x and y are never used and only y is returned. Is this intentional?
>
> tic_tac_toe.rb:59
>
>    - Check your while loop. Do all of those prints and checks need to be
>    there?
>
> Specs
>
> *Invalid Syntax.*
>
>    - Won't even run.
>    - x doesn't exist.
>    - it with no end.
>    - 'describ'
>    - Lets make sure to make sure files that are not being used are still
>    valid syntax
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buckspencer/tic_tac_toe/issues/1>.
>



-- 
-Buck Spencer

**Comment by buckspencer** [comment]
I went ahead and fixed those errors and the test runs. I need your help creating a useful test though.

**Comment by jah2488** [comment]
@buckspencer Great work! We will get more practice with tests in the coming days and weeks, but if you ever want me to help you with writing some tests for a particular assignment, come and grab me during lab time and we can pair through a few.

**Comment by buckspencer** [comment]
Okay great!

On Tue, Jan 13, 2015 at 10:32 PM, Justin Herrick <notifications@github.com>
wrote:

> @buckspencer <https://github.com/buckspencer> Great work! We will get
> more practice with tests in the coming days and weeks, but if you ever want
> me to help you with writing some tests for a particular assignment, come
> and grab me during lab time and we can pair through a few.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buckspencer/tic_tac_toe/issues/1#issuecomment-69867950>
> .
>



-- 
-Buck Spencer
